[font]
size = 16
bold.family = "Hack Nerd Font"
normal.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"

[window]
dimensions.columns = 120
dimensions.lines = 30
decorations = 'buttonless'
dynamic_padding = true
padding = { x = 0, y = 0 }


[[keyboard.bindings]]
key = "Key1"
mods = "Command"
chars = "\u001b[49;5u"

[[keyboard.bindings]]
key = "Key2"
mods = "Command"
chars = "\u001b[50;5u"

[[keyboard.bindings]]
key = "Key3"
mods = "Command"
chars = "\u001b[51;5u"

[[keyboard.bindings]]
key = "Key4"
mods = "Command"
chars = "\u001b[52;5u"

[[keyboard.bindings]]
key = "Key5"
mods = "Command"
chars = "\u001b[53;5u"

[[keyboard.bindings]]
key = "Key6"
mods = "Command"
chars = "\u001b[54;5u"

[[keyboard.bindings]]
key = "Key7"
mods = "Command"
chars = "\u001b[55;5u"

[[keyboard.bindings]]
key = "Key8"
mods = "Command"
chars = "\u001b[56;5u"

[[keyboard.bindings]]
key = "Key9"
mods = "Command"
chars = "\u001b[57;5u"


[[keyboard.bindings]]
key = 'V'
mods = "Command"
action = "Paste"

# [[keyboard.bindings]]
# key = 'C'
# mods = "Control"
# action = "Copy"
# chars = "\u0003"

[[keyboard.bindings]]
key = "`"
mods = 'Control'
chars = "\u001F"

[env]
TERM = "xterm-256color"

